
defaults:
  - hydra: default
  - model: deflow
  
slurm_id: 01113

wandb_mode: online # [offline, disabled, online]
wandb_project_name: semantic-flow

# train_data: /home3/hqlab/chenyq/project/SeFlow/data/av2/preprocess_v2/sensor/train
# val_data: /home3/hqlab/chenyq/project/SeFlow/data/av2/preprocess_v2/sensor/val
train_data: /dataset/public_dataset_nas2/av2/preprocess_v2/sensor/train
val_data: /dataset/public_dataset_nas2/av2/preprocess_v2/sensor/val

output: ${model.name}-${slurm_id}

checkpoint:
pretrained_weights: 
eval_only: False

# trainer
num_workers: 8
gpus: 1 # will change in code: torch.cuda.device_count()
sync_bn: true
batch_size: 1
epochs: 3
gradient_clip_val: 5.0

# optimizer ==> Adam
lr: 2e-6
loss_fn: seflowLoss # choices: [ff3dLoss, zeroflowLoss, deflowLoss, seflowLoss]
add_seloss: # {chamfer_dis: 1.0, static_flow_loss: 1.0, dynamic_chamfer_dis: 1.0, cluster_based_pc0pc1: 1.0}

# log settings
seed: 42069
log_every: 1 # steps epochs*dataset_size/batch_size
val_every: 1 # epochs
save_top_model: 3 # top_k model will be saved.

# -----> Model and Task Parameters
voxel_size: [0.2, 0.2, 6]
point_cloud_range: [-51.2, -51.2, -3, 51.2, 51.2, 3]
num_frames: 2